// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

import (
	"net/http"
	"os"
	"strings"
)

// ClaudeAPIController binds http requests to an api service and writes the service results to the http response
type ClaudeAPIController struct {
	service      ClaudeAPIServicer
	errorHandler ErrorHandler
}

// ClaudeAPIOption for how the controller is set up.
type ClaudeAPIOption func(*ClaudeAPIController)

// WithClaudeAPIErrorHandler inject ErrorHandler into controller
func WithClaudeAPIErrorHandler(h ErrorHandler) ClaudeAPIOption {
	return func(c *ClaudeAPIController) {
		c.errorHandler = h
	}
}

// NewClaudeAPIController creates a default api controller
func NewClaudeAPIController(s ClaudeAPIServicer, opts ...ClaudeAPIOption) *ClaudeAPIController {
	controller := &ClaudeAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ClaudeAPIController
func (c *ClaudeAPIController) Routes() Routes {
	return Routes{
		"EncodeClaudePost": Route{
			strings.ToUpper("Post"),
			"/v1/encode/claude",
			c.EncodeClaudePost,
		},
	}
}

// EncodeClaudePost - Upload text file for claude encoding
func (c *ClaudeAPIController) EncodeClaudePost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var filenameParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "filename")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "filename", Err: err}, nil)
			return
		}

		filenameParam = param
	}

	result, err := c.service.EncodeClaudePost(r.Context(), filenameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
