// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

import (
	"net/http"
	"os"
	"strings"
)

// P50kEditAPIController binds http requests to an api service and writes the service results to the http response
type P50kEditAPIController struct {
	service      P50kEditAPIServicer
	errorHandler ErrorHandler
}

// P50kEditAPIOption for how the controller is set up.
type P50kEditAPIOption func(*P50kEditAPIController)

// WithP50kEditAPIErrorHandler inject ErrorHandler into controller
func WithP50kEditAPIErrorHandler(h ErrorHandler) P50kEditAPIOption {
	return func(c *P50kEditAPIController) {
		c.errorHandler = h
	}
}

// NewP50kEditAPIController creates a default api controller
func NewP50kEditAPIController(s P50kEditAPIServicer, opts ...P50kEditAPIOption) *P50kEditAPIController {
	controller := &P50kEditAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the P50kEditAPIController
func (c *P50kEditAPIController) Routes() Routes {
	return Routes{
		"EncodeP50kEditPost": Route{
			strings.ToUpper("Post"),
			"/v1/encode/p50k_edit",
			c.EncodeP50kEditPost,
		},
	}
}

// EncodeP50kEditPost - Upload text file for p50k_edit encoding
func (c *P50kEditAPIController) EncodeP50kEditPost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var filenameParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "filename")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "filename", Err: err}, nil)
			return
		}

		filenameParam = param
	}

	result, err := c.service.EncodeP50kEditPost(r.Context(), filenameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
