// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

import (
	"net/http"
	"os"
	"strings"
)

// P50kBaseAPIController binds http requests to an api service and writes the service results to the http response
type P50kBaseAPIController struct {
	service      P50kBaseAPIServicer
	errorHandler ErrorHandler
}

// P50kBaseAPIOption for how the controller is set up.
type P50kBaseAPIOption func(*P50kBaseAPIController)

// WithP50kBaseAPIErrorHandler inject ErrorHandler into controller
func WithP50kBaseAPIErrorHandler(h ErrorHandler) P50kBaseAPIOption {
	return func(c *P50kBaseAPIController) {
		c.errorHandler = h
	}
}

// NewP50kBaseAPIController creates a default api controller
func NewP50kBaseAPIController(s P50kBaseAPIServicer, opts ...P50kBaseAPIOption) *P50kBaseAPIController {
	controller := &P50kBaseAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the P50kBaseAPIController
func (c *P50kBaseAPIController) Routes() Routes {
	return Routes{
		"EncodeP50kBasePost": Route{
			strings.ToUpper("Post"),
			"/v1/encode/p50k_base",
			c.EncodeP50kBasePost,
		},
	}
}

// EncodeP50kBasePost - Upload text file for p50k_base encoding
func (c *P50kBaseAPIController) EncodeP50kBasePost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var filenameParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "filename")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "filename", Err: err}, nil)
			return
		}

		filenameParam = param
	}

	result, err := c.service.EncodeP50kBasePost(r.Context(), filenameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
