// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

import (
	"net/http"
	"os"
	"strings"
)

// R50kBaseAPIController binds http requests to an api service and writes the service results to the http response
type R50kBaseAPIController struct {
	service      R50kBaseAPIServicer
	errorHandler ErrorHandler
}

// R50kBaseAPIOption for how the controller is set up.
type R50kBaseAPIOption func(*R50kBaseAPIController)

// WithR50kBaseAPIErrorHandler inject ErrorHandler into controller
func WithR50kBaseAPIErrorHandler(h ErrorHandler) R50kBaseAPIOption {
	return func(c *R50kBaseAPIController) {
		c.errorHandler = h
	}
}

// NewR50kBaseAPIController creates a default api controller
func NewR50kBaseAPIController(s R50kBaseAPIServicer, opts ...R50kBaseAPIOption) *R50kBaseAPIController {
	controller := &R50kBaseAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the R50kBaseAPIController
func (c *R50kBaseAPIController) Routes() Routes {
	return Routes{
		"EncodeR50kBasePost": Route{
			strings.ToUpper("Post"),
			"/v1/encode/r50k_base",
			c.EncodeR50kBasePost,
		},
	}
}

// EncodeR50kBasePost - Upload text file for r50k_base encoding
func (c *R50kBaseAPIController) EncodeR50kBasePost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var filenameParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "filename")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "filename", Err: err}, nil)
			return
		}

		filenameParam = param
	}

	result, err := c.service.EncodeR50kBasePost(r.Context(), filenameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
