// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

import (
	"net/http"
	"os"
	"strings"
)

// Cl100kBaseAPIController binds http requests to an api service and writes the service results to the http response
type Cl100kBaseAPIController struct {
	service      Cl100kBaseAPIServicer
	errorHandler ErrorHandler
}

// Cl100kBaseAPIOption for how the controller is set up.
type Cl100kBaseAPIOption func(*Cl100kBaseAPIController)

// WithCl100kBaseAPIErrorHandler inject ErrorHandler into controller
func WithCl100kBaseAPIErrorHandler(h ErrorHandler) Cl100kBaseAPIOption {
	return func(c *Cl100kBaseAPIController) {
		c.errorHandler = h
	}
}

// NewCl100kBaseAPIController creates a default api controller
func NewCl100kBaseAPIController(s Cl100kBaseAPIServicer, opts ...Cl100kBaseAPIOption) *Cl100kBaseAPIController {
	controller := &Cl100kBaseAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the Cl100kBaseAPIController
func (c *Cl100kBaseAPIController) Routes() Routes {
	return Routes{
		"EncodeCl100kBasePost": Route{
			strings.ToUpper("Post"),
			"/v1/encode/cl100k_base",
			c.EncodeCl100kBasePost,
		},
	}
}

// EncodeCl100kBasePost - Upload text file for cl100k_base encoding
func (c *Cl100kBaseAPIController) EncodeCl100kBasePost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var filenameParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "filename")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "filename", Err: err}, nil)
			return
		}

		filenameParam = param
	}

	result, err := c.service.EncodeCl100kBasePost(r.Context(), filenameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
