// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

type EncodeO200kBasePost400Response struct {

	// Error message
	Message string `json:"message,omitempty"`
}

// AssertEncodeO200kBasePost400ResponseRequired checks if the required fields are not zero-ed
func AssertEncodeO200kBasePost400ResponseRequired(obj EncodeO200kBasePost400Response) error {
	return nil
}

// AssertEncodeO200kBasePost400ResponseConstraints checks if the values respects the defined constraints
func AssertEncodeO200kBasePost400ResponseConstraints(obj EncodeO200kBasePost400Response) error {
	return nil
}
