// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

type ServerHealthGet502Response struct {

	// Service status
	Health string `json:"health,omitempty"`
}

// AssertServerHealthGet502ResponseRequired checks if the required fields are not zero-ed
func AssertServerHealthGet502ResponseRequired(obj ServerHealthGet502Response) error {
	return nil
}

// AssertServerHealthGet502ResponseConstraints checks if the values respects the defined constraints
func AssertServerHealthGet502ResponseConstraints(obj ServerHealthGet502Response) error {
	return nil
}
