// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nulladmin.com aitokenizer
 *
 * Aitokenizer is a Nulladmin.com microservice which performs input tokenization for AI workloads. It supports various encodings used by OpenAI, Anthropic and others.
 *
 * API version: 1.0.0
 */

package aitokenizer

type ServerVersionGet200Response struct {

	// Name of the service
	ServiceName string `json:"ServiceName,omitempty"`

	// Program version. Typically this is the git tag of the current commit, e.g. \"1.0.0'.
	Version string `json:"Version,omitempty"`

	// Build revision, e.g. the short git commit hash
	Revision string `json:"Revision,omitempty"`

	// Git branch
	Branch string `json:"Branch,omitempty"`

	// Build date
	BuildDate string `json:"BuildDate,omitempty"`

	// Go version
	GoVersion string `json:"GoVersion,omitempty"`

	// Machine architecture
	OSArch string `json:"OSArch,omitempty"`
}

// AssertServerVersionGet200ResponseRequired checks if the required fields are not zero-ed
func AssertServerVersionGet200ResponseRequired(obj ServerVersionGet200Response) error {
	return nil
}

// AssertServerVersionGet200ResponseConstraints checks if the values respects the defined constraints
func AssertServerVersionGet200ResponseConstraints(obj ServerVersionGet200Response) error {
	return nil
}
